// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3v7aWScShKJMyXQkHmLe8O3BLsGyY40',
    appId: '1:1063270362786:web:b8fb5191fdf06a76c9f1fb',
    messagingSenderId: '1063270362786',
    projectId: 'postmark-telemetry',
    storageBucket: 'postmark-telemetry.firebasestorage.app',
    authDomain: 'postmark-telemetry.firebaseapp.com',
    measurementId: 'G-C7XLHKXP4V',
    databaseURL: 'https://postmark-telemetry-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qqWUOsuyTKXmbW0-La_cf-HtcEAo5LA',
    appId: '1:1063270362786:android:38fa07f398890674c9f1fb',
    messagingSenderId: '1063270362786',
    projectId: 'postmark-telemetry',
    storageBucket: 'postmark-telemetry.firebasestorage.app',
    databaseURL: 'https://postmark-telemetry-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqpX3EBQOn0urfS9CJco1Umc94ABL3Yt8',
    appId: '1:1063270362786:ios:de9dddd5e2202ec8c9f1fb',
    messagingSenderId: '1063270362786',
    projectId: 'postmark-telemetry',
    storageBucket: 'postmark-telemetry.firebasestorage.app',
    androidClientId: '1063270362786-4r5rf3abrg42aigufqtqng739d7qfrdh.apps.googleusercontent.com',
    iosClientId: '1063270362786-d002fsnhcs3s01tq0nv0ejgd0qhj9omp.apps.googleusercontent.com',
    iosBundleId: 'com.example.postmark',
    databaseURL: 'https://postmark-telemetry-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqpX3EBQOn0urfS9CJco1Umc94ABL3Yt8',
    appId: '1:1063270362786:ios:de9dddd5e2202ec8c9f1fb',
    messagingSenderId: '1063270362786',
    projectId: 'postmark-telemetry',
    storageBucket: 'postmark-telemetry.firebasestorage.app',
    androidClientId: '1063270362786-4r5rf3abrg42aigufqtqng739d7qfrdh.apps.googleusercontent.com',
    iosClientId: '1063270362786-d002fsnhcs3s01tq0nv0ejgd0qhj9omp.apps.googleusercontent.com',
    iosBundleId: 'com.example.postmark',
    databaseURL: 'https://postmark-telemetry-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3v7aWScShKJMyXQkHmLe8O3BLsGyY40',
    appId: '1:1063270362786:web:7548599c34a7537fc9f1fb',
    messagingSenderId: '1063270362786',
    projectId: 'postmark-telemetry',
    authDomain: 'postmark-telemetry.firebaseapp.com',
    storageBucket: 'postmark-telemetry.firebasestorage.app',
    measurementId: 'G-C7XLHKXP4V',
    databaseURL: 'https://postmark-telemetry-default-rtdb.firebaseio.com',
  );
}
