// Noto Animated Emojis Data List
// Automatically generated from Google Noto Emoji Animation database.

class NotoEmoji {
  final String char;
  final String code;
  final List<String> tags;

  const NotoEmoji({
    required this.char,
    required this.code,
    required this.tags,
  });
}

class NotoEmojiData {
  static const Map<String, List<NotoEmoji>> categories = {
    'Smileys': [
      NotoEmoji(char: '😀', code: '1f600', tags: [':smile:']),
      NotoEmoji(char: '😃', code: '1f603', tags: [':smile-with-big-eyes:']),
      NotoEmoji(char: '😄', code: '1f604', tags: [':grin:']),
      NotoEmoji(char: '😁', code: '1f601', tags: [':grinning:']),
      NotoEmoji(char: '😆', code: '1f606', tags: [':laughing:']),
      NotoEmoji(char: '😅', code: '1f605', tags: [':grin-sweat:']),
      NotoEmoji(char: '😂', code: '1f602', tags: [':joy:']),
      NotoEmoji(char: '🤣', code: '1f923', tags: [':rofl:']),
      NotoEmoji(char: '😭', code: '1f62d', tags: [':loudly-crying:']),
      NotoEmoji(char: '😉', code: '1f609', tags: [':wink:']),
      NotoEmoji(char: '😗', code: '1f617', tags: [':kissing:']),
      NotoEmoji(char: '😙', code: '1f619', tags: [':kissing-smiling-eyes:']),
      NotoEmoji(char: '😚', code: '1f61a', tags: [':kissing-closed-eyes:']),
      NotoEmoji(char: '😘', code: '1f618', tags: [':kissing-heart:']),
      NotoEmoji(char: '🥰', code: '1f970', tags: [':heart-face:', ':3-hearts:']),
      NotoEmoji(char: '😍', code: '1f60d', tags: [':heart-eyes:']),
      NotoEmoji(char: '🤩', code: '1f929', tags: [':star-struck:']),
      NotoEmoji(char: '🥳', code: '1f973', tags: [':partying-face:']),
      NotoEmoji(char: '🫠', code: '1fae0', tags: [':melting:']),
      NotoEmoji(char: '🙃', code: '1f643', tags: [':upside-down-face:']),
      NotoEmoji(char: '🙂', code: '1f642', tags: [':slightly-happy:']),
      NotoEmoji(char: '🥲', code: '1f972', tags: [':happy-cry:']),
      NotoEmoji(char: '🥹', code: '1f979', tags: [':holding-back-tears:']),
      NotoEmoji(char: '😊', code: '1f60a', tags: [':blush:']),
      NotoEmoji(char: '☺️', code: '263a_fe0f', tags: [':warm-smile:']),
      NotoEmoji(char: '😌', code: '1f60c', tags: [':relieved:']),
      NotoEmoji(char: '🙂‍↕️', code: '1f642_200d_2195_fe0f', tags: [':head-nod:']),
      NotoEmoji(char: '🙂‍↔️', code: '1f642_200d_2194_fe0f', tags: [':head-shake:']),
      NotoEmoji(char: '😏', code: '1f60f', tags: [':smirk:']),
      NotoEmoji(char: '🤤', code: '1f924', tags: [':drool:']),
      NotoEmoji(char: '😋', code: '1f60b', tags: [':yum:']),
      NotoEmoji(char: '😛', code: '1f61b', tags: [':stuck-out-tongue:']),
      NotoEmoji(char: '😝', code: '1f61d', tags: [':squinting-tongue:']),
      NotoEmoji(char: '😜', code: '1f61c', tags: [':winky-tongue:']),
      NotoEmoji(char: '🤪', code: '1f92a', tags: [':zany-face:']),
      NotoEmoji(char: '🫪', code: '1faea', tags: [':distorted-face:']),
      NotoEmoji(char: '😔', code: '1f614', tags: [':pensive:']),
      NotoEmoji(char: '🥺', code: '1f97a', tags: [':pleading:']),
      NotoEmoji(char: '😬', code: '1f62c', tags: [':grimacing:']),
      NotoEmoji(char: '😑', code: '1f611', tags: [':expressionless:']),
      NotoEmoji(char: '😐', code: '1f610', tags: [':neutral-face:']),
      NotoEmoji(char: '😶', code: '1f636', tags: [':mouth-none:']),
      NotoEmoji(char: '😶‍🌫️', code: '1f636_200d_1f32b_fe0f', tags: [':face-in-clouds:', ':lost:']),
      NotoEmoji(char: '🫥', code: '1fae5', tags: [':dotted-line-face:', ':invisible:']),
      NotoEmoji(char: '🤐', code: '1f910', tags: [':zipper-face:']),
      NotoEmoji(char: '🫡', code: '1fae1', tags: [':salute:']),
      NotoEmoji(char: '🤔', code: '1f914', tags: [':thinking-face:']),
      NotoEmoji(char: '🤫', code: '1f92b', tags: [':shushing-face:']),
      NotoEmoji(char: '🫢', code: '1fae2', tags: [':hand-over-mouth:']),
      NotoEmoji(char: '🤭', code: '1f92d', tags: [':smiling-eyes-with-hand-over-mouth:', ':chuckling:']),
      NotoEmoji(char: '🥱', code: '1f971', tags: [':yawn:']),
      NotoEmoji(char: '🤗', code: '1f917', tags: [':hug-face:']),
      NotoEmoji(char: '🫣', code: '1fae3', tags: [':peeking:']),
      NotoEmoji(char: '😱', code: '1f631', tags: [':screaming:']),
      NotoEmoji(char: '🤨', code: '1f928', tags: [':raised-eyebrow:']),
      NotoEmoji(char: '🧐', code: '1f9d0', tags: [':monocle:']),
      NotoEmoji(char: '😒', code: '1f612', tags: [':unamused:']),
      NotoEmoji(char: '🙄', code: '1f644', tags: [':rolling-eyes:']),
      NotoEmoji(char: '😮‍💨', code: '1f62e_200d_1f4a8', tags: [':exhale:']),
      NotoEmoji(char: '😤', code: '1f624', tags: [':triumph:']),
      NotoEmoji(char: '😠', code: '1f620', tags: [':angry:']),
      NotoEmoji(char: '😡', code: '1f621', tags: [':rage:']),
      NotoEmoji(char: '🤬', code: '1f92c', tags: [':cursing:']),
      NotoEmoji(char: '😞', code: '1f61e', tags: [':sad:']),
      NotoEmoji(char: '😓', code: '1f613', tags: [':sweat:', ':downcast:']),
      NotoEmoji(char: '😟', code: '1f61f', tags: [':worried:']),
      NotoEmoji(char: '😥', code: '1f625', tags: [':concerned:']),
      NotoEmoji(char: '😢', code: '1f622', tags: [':cry:']),
      NotoEmoji(char: '☹️', code: '2639_fe0f', tags: [':big-frown:']),
      NotoEmoji(char: '🙁', code: '1f641', tags: [':frown:']),
      NotoEmoji(char: '🫤', code: '1fae4', tags: [':diagonal-mouth:']),
      NotoEmoji(char: '😕', code: '1f615', tags: [':slightly-frowning:']),
      NotoEmoji(char: '😰', code: '1f630', tags: [':anxious-with-sweat:']),
      NotoEmoji(char: '😨', code: '1f628', tags: [':scared:']),
      NotoEmoji(char: '😧', code: '1f627', tags: [':anguished:']),
      NotoEmoji(char: '😦', code: '1f626', tags: [':gasp:']),
      NotoEmoji(char: '😮', code: '1f62e', tags: [':mouth-open:']),
      NotoEmoji(char: '😯', code: '1f62f', tags: [':surprised:', ':hushed:']),
      NotoEmoji(char: '😲', code: '1f632', tags: [':astonished:']),
      NotoEmoji(char: '😳', code: '1f633', tags: [':flushed:']),
      NotoEmoji(char: '🤯', code: '1f92f', tags: [':mind-blown:', ':exploding-head:']),
      NotoEmoji(char: '😖', code: '1f616', tags: [':scrunched-mouth:', ':confounded:', ':zigzag-mouth:']),
      NotoEmoji(char: '😣', code: '1f623', tags: [':scrunched-eyes:', ':persevering:']),
      NotoEmoji(char: '😩', code: '1f629', tags: [':weary:']),
      NotoEmoji(char: '😫', code: '1f62b', tags: [':distraught:']),
      NotoEmoji(char: '😵', code: '1f635', tags: [':x-eyes:']),
      NotoEmoji(char: '😵‍💫', code: '1f635_200d_1f4ab', tags: [':dizzy-face:']),
      NotoEmoji(char: '🫨', code: '1fae8', tags: [':shaking-face:']),
      NotoEmoji(char: '🥴', code: '1f974', tags: [':woozy:']),
      NotoEmoji(char: '🥵', code: '1f975', tags: [':hot-face:', ':sweat-face:']),
      NotoEmoji(char: '🥶', code: '1f976', tags: [':cold-face:']),
      NotoEmoji(char: '🤢', code: '1f922', tags: [':sick:', ':nauseated:']),
      NotoEmoji(char: '🤮', code: '1f92e', tags: [':vomit:']),
      NotoEmoji(char: '🫩', code: '1fae9', tags: [':tired:', ':bags-under-eyes:']),
      NotoEmoji(char: '😴', code: '1f634', tags: [':sleep:']),
      NotoEmoji(char: '😪', code: '1f62a', tags: [':sleepy:']),
      NotoEmoji(char: '🤧', code: '1f927', tags: [':sneeze:']),
      NotoEmoji(char: '🤒', code: '1f912', tags: [':thermometer-face:']),
      NotoEmoji(char: '🤕', code: '1f915', tags: [':bandage-face:']),
      NotoEmoji(char: '😷', code: '1f637', tags: [':mask:']),
      NotoEmoji(char: '🤥', code: '1f925', tags: [':liar:']),
      NotoEmoji(char: '😇', code: '1f607', tags: [':halo:', ':innocent:']),
      NotoEmoji(char: '🤠', code: '1f920', tags: [':cowboy:']),
      NotoEmoji(char: '🤑', code: '1f911', tags: [':money-face:']),
      NotoEmoji(char: '🤓', code: '1f913', tags: [':nerd-face:']),
      NotoEmoji(char: '😎', code: '1f60e', tags: [':sunglasses-face:']),
      NotoEmoji(char: '🥸', code: '1f978', tags: [':disguise:']),
      NotoEmoji(char: '🤡', code: '1f921', tags: [':clown:']),
      NotoEmoji(char: '💩', code: '1f4a9', tags: [':poop:']),
      NotoEmoji(char: '😈', code: '1f608', tags: [':imp-smile:']),
      NotoEmoji(char: '👿', code: '1f47f', tags: [':imp-frown:']),
      NotoEmoji(char: '👻', code: '1f47b', tags: [':ghost:']),
      NotoEmoji(char: '💀', code: '1f480', tags: [':skull:']),
      NotoEmoji(char: '🤖', code: '1f916', tags: [':robot:']),
      NotoEmoji(char: '👹', code: '1f479', tags: [':ogre:']),
      NotoEmoji(char: '☃️', code: '2603_fe0f', tags: [':snowman-with-snow:']),
      NotoEmoji(char: '⛄', code: '26c4', tags: [':snowman:']),
      NotoEmoji(char: '👽', code: '1f47d', tags: [':alien:']),
      NotoEmoji(char: '👾', code: '1f47e', tags: [':alien-monster:']),
      NotoEmoji(char: '🌚', code: '1f31a', tags: [':moon-face-new:']),
      NotoEmoji(char: '🌝', code: '1f31d', tags: [':moon-face-full:']),
      NotoEmoji(char: '🌞', code: '1f31e', tags: [':sun-with-face:']),
      NotoEmoji(char: '🌛', code: '1f31b', tags: [':moon-face-first-quarter:']),
      NotoEmoji(char: '🌜', code: '1f31c', tags: [':moon-face-last-quarter:']),
      NotoEmoji(char: '😺', code: '1f63a', tags: [':smiley-cat:']),
      NotoEmoji(char: '😸', code: '1f638', tags: [':smile-cat:']),
      NotoEmoji(char: '😹', code: '1f639', tags: [':joy-cat:']),
      NotoEmoji(char: '😻', code: '1f63b', tags: [':heart-eyes-cat:']),
      NotoEmoji(char: '😼', code: '1f63c', tags: [':smirk-cat:']),
      NotoEmoji(char: '😽', code: '1f63d', tags: [':kissing-cat:']),
      NotoEmoji(char: '🙀', code: '1f640', tags: [':scream-cat:']),
      NotoEmoji(char: '😿', code: '1f63f', tags: [':crying-cat-face:']),
      NotoEmoji(char: '😾', code: '1f63e', tags: [':pouting-cat:']),
      NotoEmoji(char: '🙈', code: '1f648', tags: [':see-no-evil-monkey:']),
      NotoEmoji(char: '🙉', code: '1f649', tags: [':hear-no-evil-monkey:']),
      NotoEmoji(char: '🙊', code: '1f64a', tags: [':speak-no-evil-monkey:']),
      NotoEmoji(char: '⭐', code: '2b50', tags: [':star:']),
      NotoEmoji(char: '🌟', code: '1f31f', tags: [':glowing-star:']),
      NotoEmoji(char: '✨', code: '2728', tags: [':sparkles:']),
      NotoEmoji(char: '⚡', code: '26a1', tags: [':electricity:', ':zap:', ':lightning:']),
      NotoEmoji(char: '💥', code: '1f4a5', tags: [':collision:']),
      NotoEmoji(char: '🫯', code: '1faef', tags: [':fight:']),
      NotoEmoji(char: '🕳️', code: '1f573_fe0f', tags: [':hole:']),
      NotoEmoji(char: '🔥', code: '1f525', tags: [':fire:', ':burn:', ':lit:']),
      NotoEmoji(char: '💯', code: '1f4af', tags: [':100:', ':one-hundred:', ':hundred:', ':points:']),
      NotoEmoji(char: '🎉', code: '1f389', tags: [':party-popper:']),
      NotoEmoji(char: '🎊', code: '1f38a', tags: [':confetti-ball:']),
      NotoEmoji(char: '❤️', code: '2764_fe0f', tags: [':red-heart:']),
      NotoEmoji(char: '🧡', code: '1f9e1', tags: [':orange-heart:']),
      NotoEmoji(char: '💛', code: '1f49b', tags: [':yellow-heart:']),
      NotoEmoji(char: '💚', code: '1f49a', tags: [':green-heart:']),
      NotoEmoji(char: '🩵', code: '1fa75', tags: [':light-blue-heart:']),
      NotoEmoji(char: '💙', code: '1f499', tags: [':blue-heart:']),
      NotoEmoji(char: '💜', code: '1f49c', tags: [':purple-heart:']),
      NotoEmoji(char: '🤎', code: '1f90e', tags: [':brown-heart:']),
      NotoEmoji(char: '🖤', code: '1f5a4', tags: [':black-heart:']),
      NotoEmoji(char: '🩶', code: '1fa76', tags: [':grey-heart:']),
      NotoEmoji(char: '🤍', code: '1f90d', tags: [':white-heart:']),
      NotoEmoji(char: '🩷', code: '1fa77', tags: [':pink-heart:']),
      NotoEmoji(char: '💘', code: '1f498', tags: [':cupid:']),
      NotoEmoji(char: '💝', code: '1f49d', tags: [':gift-heart:']),
      NotoEmoji(char: '💖', code: '1f496', tags: [':sparkling-heart:']),
      NotoEmoji(char: '💗', code: '1f497', tags: [':heart-grow:']),
      NotoEmoji(char: '💓', code: '1f493', tags: [':beating-heart:']),
      NotoEmoji(char: '💞', code: '1f49e', tags: [':revolving-hearts:']),
      NotoEmoji(char: '💕', code: '1f495', tags: [':two-hearts:']),
      NotoEmoji(char: '💌', code: '1f48c', tags: [':love-letter:']),
      NotoEmoji(char: '💟', code: '1f49f', tags: [':heart-box:']),
      NotoEmoji(char: '♥️', code: '2665_fe0f', tags: [':heart:']),
      NotoEmoji(char: '❣️', code: '2763_fe0f', tags: [':heart-exclamation-point:']),
      NotoEmoji(char: '❤️‍🩹', code: '2764_fe0f_200d_1fa79', tags: [':bandaged-heart:']),
      NotoEmoji(char: '💔', code: '1f494', tags: [':broken-heart:']),
      NotoEmoji(char: '❤️‍🔥', code: '2764_fe0f_200d_1f525', tags: [':fire-heart:']),
      NotoEmoji(char: '💋', code: '1f48b', tags: [':kiss:']),
      NotoEmoji(char: '🫂', code: '1fac2', tags: [':hugging:']),
      NotoEmoji(char: '🗣️', code: '1f5e3_fe0f', tags: [':speaking-head:']),
      NotoEmoji(char: '👣', code: '1f463', tags: [':footprints:']),
      NotoEmoji(char: '🫆', code: '1fac6', tags: [':fingerprint:']),
      NotoEmoji(char: '🧠', code: '1f9e0', tags: [':brain:']),
      NotoEmoji(char: '🫀', code: '1fac0', tags: [':anatomical-heart:']),
      NotoEmoji(char: '🩸', code: '1fa78', tags: [':blood:']),
      NotoEmoji(char: '🦠', code: '1f9a0', tags: [':microbe:', ':virus:']),
      NotoEmoji(char: '🦴', code: '1f9b4', tags: [':bone:']),
      NotoEmoji(char: '👀', code: '1f440', tags: [':eyes:']),
      NotoEmoji(char: '👁️', code: '1f441_fe0f', tags: [':eye:']),
      NotoEmoji(char: '🫦', code: '1fae6', tags: [':biting-lip:']),
      NotoEmoji(char: '👃', code: '1f443', tags: [':nose:']),
      NotoEmoji(char: '👃🏻', code: '1f443_1f3fb', tags: [':nose:']),
      NotoEmoji(char: '👃🏼', code: '1f443_1f3fc', tags: [':nose:']),
      NotoEmoji(char: '👃🏽', code: '1f443_1f3fd', tags: [':nose:']),
      NotoEmoji(char: '👃🏾', code: '1f443_1f3fe', tags: [':nose:']),
      NotoEmoji(char: '👃🏿', code: '1f443_1f3ff', tags: [':nose:']),
      NotoEmoji(char: '👂', code: '1f442', tags: [':ear:']),
      NotoEmoji(char: '👂🏻', code: '1f442_1f3fb', tags: [':ear:']),
      NotoEmoji(char: '👂🏼', code: '1f442_1f3fc', tags: [':ear:']),
      NotoEmoji(char: '👂🏽', code: '1f442_1f3fd', tags: [':ear:']),
      NotoEmoji(char: '👂🏾', code: '1f442_1f3fe', tags: [':ear:']),
      NotoEmoji(char: '👂🏿', code: '1f442_1f3ff', tags: [':ear:']),
      NotoEmoji(char: '🦻', code: '1f9bb', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦻🏻', code: '1f9bb_1f3fb', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦻🏼', code: '1f9bb_1f3fc', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦻🏽', code: '1f9bb_1f3fd', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦻🏾', code: '1f9bb_1f3fe', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦻🏿', code: '1f9bb_1f3ff', tags: [':hearing-aid:']),
      NotoEmoji(char: '🦶', code: '1f9b6', tags: [':foot:']),
      NotoEmoji(char: '🦶🏻', code: '1f9b6_1f3fb', tags: [':foot:']),
      NotoEmoji(char: '🦶🏼', code: '1f9b6_1f3fc', tags: [':foot:']),
      NotoEmoji(char: '🦶🏽', code: '1f9b6_1f3fd', tags: [':foot:']),
      NotoEmoji(char: '🦶🏾', code: '1f9b6_1f3fe', tags: [':foot:']),
      NotoEmoji(char: '🦶🏿', code: '1f9b6_1f3ff', tags: [':foot:']),
      NotoEmoji(char: '🦵', code: '1f9b5', tags: [':leg:']),
      NotoEmoji(char: '🦵🏻', code: '1f9b5_1f3fb', tags: [':leg:']),
      NotoEmoji(char: '🦵🏼', code: '1f9b5_1f3fc', tags: [':leg:']),
      NotoEmoji(char: '🦵🏽', code: '1f9b5_1f3fd', tags: [':leg:']),
      NotoEmoji(char: '🦵🏾', code: '1f9b5_1f3fe', tags: [':leg:']),
      NotoEmoji(char: '🦵🏿', code: '1f9b5_1f3ff', tags: [':leg:']),
      NotoEmoji(char: '🦿', code: '1f9bf', tags: [':leg-mechanical:']),
      NotoEmoji(char: '🦾', code: '1f9be', tags: [':arm-mechanical:']),
      NotoEmoji(char: '💪', code: '1f4aa', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '💪🏻', code: '1f4aa_1f3fb', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '💪🏼', code: '1f4aa_1f3fc', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '💪🏽', code: '1f4aa_1f3fd', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '💪🏾', code: '1f4aa_1f3fe', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '💪🏿', code: '1f4aa_1f3ff', tags: [':muscle:', ':flex:', ':bicep:', ':strong:']),
      NotoEmoji(char: '👏', code: '1f44f', tags: [':clap:']),
      NotoEmoji(char: '👏🏻', code: '1f44f_1f3fb', tags: [':clap:']),
      NotoEmoji(char: '👏🏼', code: '1f44f_1f3fc', tags: [':clap:']),
      NotoEmoji(char: '👏🏽', code: '1f44f_1f3fd', tags: [':clap:']),
      NotoEmoji(char: '👏🏾', code: '1f44f_1f3fe', tags: [':clap:']),
      NotoEmoji(char: '👏🏿', code: '1f44f_1f3ff', tags: [':clap:']),
      NotoEmoji(char: '👍', code: '1f44d', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👍🏻', code: '1f44d_1f3fb', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👍🏼', code: '1f44d_1f3fc', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👍🏽', code: '1f44d_1f3fd', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👍🏾', code: '1f44d_1f3fe', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👍🏿', code: '1f44d_1f3ff', tags: [':thumbs-up:', ':+1:']),
      NotoEmoji(char: '👎', code: '1f44e', tags: [':thumbs-down:']),
      NotoEmoji(char: '👎🏻', code: '1f44e_1f3fb', tags: [':thumbs-down:']),
      NotoEmoji(char: '👎🏼', code: '1f44e_1f3fc', tags: [':thumbs-down:']),
      NotoEmoji(char: '👎🏽', code: '1f44e_1f3fd', tags: [':thumbs-down:']),
      NotoEmoji(char: '👎🏾', code: '1f44e_1f3fe', tags: [':thumbs-down:']),
      NotoEmoji(char: '👎🏿', code: '1f44e_1f3ff', tags: [':thumbs-down:']),
      NotoEmoji(char: '🫶', code: '1faf6', tags: [':heart-hands:']),
      NotoEmoji(char: '🫶🏻', code: '1faf6_1f3fb', tags: [':heart-hands:']),
      NotoEmoji(char: '🫶🏼', code: '1faf6_1f3fc', tags: [':heart-hands:']),
      NotoEmoji(char: '🫶🏽', code: '1faf6_1f3fd', tags: [':heart-hands:']),
      NotoEmoji(char: '🫶🏾', code: '1faf6_1f3fe', tags: [':heart-hands:']),
      NotoEmoji(char: '🫶🏿', code: '1faf6_1f3ff', tags: [':heart-hands:']),
      NotoEmoji(char: '🙌', code: '1f64c', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '🙌🏻', code: '1f64c_1f3fb', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '🙌🏼', code: '1f64c_1f3fc', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '🙌🏽', code: '1f64c_1f3fd', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '🙌🏾', code: '1f64c_1f3fe', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '🙌🏿', code: '1f64c_1f3ff', tags: [':raising-hands:', ':hooray:']),
      NotoEmoji(char: '👐', code: '1f450', tags: [':open-hands:']),
      NotoEmoji(char: '👐🏻', code: '1f450_1f3fb', tags: [':open-hands:']),
      NotoEmoji(char: '👐🏼', code: '1f450_1f3fc', tags: [':open-hands:']),
      NotoEmoji(char: '👐🏽', code: '1f450_1f3fd', tags: [':open-hands:']),
      NotoEmoji(char: '👐🏾', code: '1f450_1f3fe', tags: [':open-hands:']),
      NotoEmoji(char: '👐🏿', code: '1f450_1f3ff', tags: [':open-hands:']),
      NotoEmoji(char: '🤲', code: '1f932', tags: [':palms-up:']),
      NotoEmoji(char: '🤲🏻', code: '1f932_1f3fb', tags: [':palms-up:']),
      NotoEmoji(char: '🤲🏼', code: '1f932_1f3fc', tags: [':palms-up:']),
      NotoEmoji(char: '🤲🏽', code: '1f932_1f3fd', tags: [':palms-up:']),
      NotoEmoji(char: '🤲🏾', code: '1f932_1f3fe', tags: [':palms-up:']),
      NotoEmoji(char: '🤲🏿', code: '1f932_1f3ff', tags: [':palms-up:']),
      NotoEmoji(char: '🤜', code: '1f91c', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤜🏻', code: '1f91c_1f3fb', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤜🏼', code: '1f91c_1f3fc', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤜🏽', code: '1f91c_1f3fd', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤜🏾', code: '1f91c_1f3fe', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤜🏿', code: '1f91c_1f3ff', tags: [':fist-rightwards:']),
      NotoEmoji(char: '🤛', code: '1f91b', tags: [':fist-leftwards:']),
      NotoEmoji(char: '🤛🏻', code: '1f91b_1f3fb', tags: [':fist-leftwards:']),
      NotoEmoji(char: '🤛🏼', code: '1f91b_1f3fc', tags: [':fist-leftwards:']),
      NotoEmoji(char: '🤛🏽', code: '1f91b_1f3fd', tags: [':fist-leftwards:']),
      NotoEmoji(char: '🤛🏾', code: '1f91b_1f3fe', tags: [':fist-leftwards:']),
      NotoEmoji(char: '🤛🏿', code: '1f91b_1f3ff', tags: [':fist-leftwards:']),
      NotoEmoji(char: '✊', code: '270a', tags: [':raised-fist:']),
      NotoEmoji(char: '✊🏻', code: '270a_1f3fb', tags: [':raised-fist:']),
      NotoEmoji(char: '✊🏼', code: '270a_1f3fc', tags: [':raised-fist:']),
      NotoEmoji(char: '✊🏽', code: '270a_1f3fd', tags: [':raised-fist:']),
      NotoEmoji(char: '✊🏾', code: '270a_1f3fe', tags: [':raised-fist:']),
      NotoEmoji(char: '✊🏿', code: '270a_1f3ff', tags: [':raised-fist:']),
      NotoEmoji(char: '👊', code: '1f44a', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '👊🏻', code: '1f44a_1f3fb', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '👊🏼', code: '1f44a_1f3fc', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '👊🏽', code: '1f44a_1f3fd', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '👊🏾', code: '1f44a_1f3fe', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '👊🏿', code: '1f44a_1f3ff', tags: [':fist:', ':bump:']),
      NotoEmoji(char: '🫳', code: '1faf3', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫳🏻', code: '1faf3_1f3fb', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫳🏼', code: '1faf3_1f3fc', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫳🏽', code: '1faf3_1f3fd', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫳🏾', code: '1faf3_1f3fe', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫳🏿', code: '1faf3_1f3ff', tags: [':palm-down:', ':drop:']),
      NotoEmoji(char: '🫴', code: '1faf4', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫴🏻', code: '1faf4_1f3fb', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫴🏼', code: '1faf4_1f3fc', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫴🏽', code: '1faf4_1f3fd', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫴🏾', code: '1faf4_1f3fe', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫴🏿', code: '1faf4_1f3ff', tags: [':palm-up:', ':throw:']),
      NotoEmoji(char: '🫱', code: '1faf1', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫱🏻', code: '1faf1_1f3fb', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫱🏼', code: '1faf1_1f3fc', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫱🏽', code: '1faf1_1f3fd', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫱🏾', code: '1faf1_1f3fe', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫱🏿', code: '1faf1_1f3ff', tags: [':rightwards-hand:']),
      NotoEmoji(char: '🫲', code: '1faf2', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫲🏻', code: '1faf2_1f3fb', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫲🏼', code: '1faf2_1f3fc', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫲🏽', code: '1faf2_1f3fd', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫲🏾', code: '1faf2_1f3fe', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫲🏿', code: '1faf2_1f3ff', tags: [':leftwards-hand:']),
      NotoEmoji(char: '🫸', code: '1faf8', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫸🏻', code: '1faf8_1f3fb', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫸🏼', code: '1faf8_1f3fc', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫸🏽', code: '1faf8_1f3fd', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫸🏾', code: '1faf8_1f3fe', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫸🏿', code: '1faf8_1f3ff', tags: [':push-rightwards:']),
      NotoEmoji(char: '🫷', code: '1faf7', tags: [':push-leftwards:']),
      NotoEmoji(char: '🫷🏻', code: '1faf7_1f3fb', tags: [':push-leftwards:']),
      NotoEmoji(char: '🫷🏼', code: '1faf7_1f3fc', tags: [':push-leftwards:']),
      NotoEmoji(char: '🫷🏽', code: '1faf7_1f3fd', tags: [':push-leftwards:']),
      NotoEmoji(char: '🫷🏾', code: '1faf7_1f3fe', tags: [':push-leftwards:']),
      NotoEmoji(char: '🫷🏿', code: '1faf7_1f3ff', tags: [':push-leftwards:']),
      NotoEmoji(char: '👋', code: '1f44b', tags: [':wave:']),
      NotoEmoji(char: '👋🏻', code: '1f44b_1f3fb', tags: [':wave:']),
      NotoEmoji(char: '👋🏼', code: '1f44b_1f3fc', tags: [':wave:']),
      NotoEmoji(char: '👋🏽', code: '1f44b_1f3fd', tags: [':wave:']),
      NotoEmoji(char: '👋🏾', code: '1f44b_1f3fe', tags: [':wave:']),
      NotoEmoji(char: '👋🏿', code: '1f44b_1f3ff', tags: [':wave:']),
      NotoEmoji(char: '🤚', code: '1f91a', tags: [':back-hand:']),
      NotoEmoji(char: '🤚🏻', code: '1f91a_1f3fb', tags: [':back-hand:']),
      NotoEmoji(char: '🤚🏼', code: '1f91a_1f3fc', tags: [':back-hand:']),
      NotoEmoji(char: '🤚🏽', code: '1f91a_1f3fd', tags: [':back-hand:']),
      NotoEmoji(char: '🤚🏾', code: '1f91a_1f3fe', tags: [':back-hand:']),
      NotoEmoji(char: '🤚🏿', code: '1f91a_1f3ff', tags: [':back-hand:']),
      NotoEmoji(char: '🖐️', code: '1f590_fe0f', tags: [':palm:']),
      NotoEmoji(char: '🖐🏻', code: '1f590_1f3fb', tags: [':palm:']),
      NotoEmoji(char: '🖐🏼', code: '1f590_1f3fc', tags: [':palm:']),
      NotoEmoji(char: '🖐🏽', code: '1f590_1f3fd', tags: [':palm:']),
      NotoEmoji(char: '🖐🏾', code: '1f590_1f3fe', tags: [':palm:']),
      NotoEmoji(char: '🖐🏿', code: '1f590_1f3ff', tags: [':palm:']),
      NotoEmoji(char: '✋', code: '270b', tags: [':raised-hand:']),
      NotoEmoji(char: '✋🏻', code: '270b_1f3fb', tags: [':raised-hand:']),
      NotoEmoji(char: '✋🏼', code: '270b_1f3fc', tags: [':raised-hand:']),
      NotoEmoji(char: '✋🏽', code: '270b_1f3fd', tags: [':raised-hand:']),
      NotoEmoji(char: '✋🏾', code: '270b_1f3fe', tags: [':raised-hand:']),
      NotoEmoji(char: '✋🏿', code: '270b_1f3ff', tags: [':raised-hand:']),
      NotoEmoji(char: '🖖', code: '1f596', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🖖🏻', code: '1f596_1f3fb', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🖖🏼', code: '1f596_1f3fc', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🖖🏽', code: '1f596_1f3fd', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🖖🏾', code: '1f596_1f3fe', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🖖🏿', code: '1f596_1f3ff', tags: [':vulcan:', ':prosper:', ':spock:']),
      NotoEmoji(char: '🤟', code: '1f91f', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤟🏻', code: '1f91f_1f3fb', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤟🏼', code: '1f91f_1f3fc', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤟🏽', code: '1f91f_1f3fd', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤟🏾', code: '1f91f_1f3fe', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤟🏿', code: '1f91f_1f3ff', tags: [':love-you-gesture:']),
      NotoEmoji(char: '🤘', code: '1f918', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '🤘🏻', code: '1f918_1f3fb', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '🤘🏼', code: '1f918_1f3fc', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '🤘🏽', code: '1f918_1f3fd', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '🤘🏾', code: '1f918_1f3fe', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '🤘🏿', code: '1f918_1f3ff', tags: [':metal:', ':horns:']),
      NotoEmoji(char: '✌️', code: '270c_fe0f', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '✌🏻', code: '270c_1f3fb', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '✌🏼', code: '270c_1f3fc', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '✌🏽', code: '270c_1f3fd', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '✌🏾', code: '270c_1f3fe', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '✌🏿', code: '270c_1f3ff', tags: [':victory:', ':v:', ':peace-hand:']),
      NotoEmoji(char: '🤞', code: '1f91e', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🤞🏻', code: '1f91e_1f3fb', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🤞🏼', code: '1f91e_1f3fc', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🤞🏽', code: '1f91e_1f3fd', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🤞🏾', code: '1f91e_1f3fe', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🤞🏿', code: '1f91e_1f3ff', tags: [':crossed-fingers:']),
      NotoEmoji(char: '🫰', code: '1faf0', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🫰🏻', code: '1faf0_1f3fb', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🫰🏼', code: '1faf0_1f3fc', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🫰🏽', code: '1faf0_1f3fd', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🫰🏾', code: '1faf0_1f3fe', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🫰🏿', code: '1faf0_1f3ff', tags: [':hand-with-index-finger-and-thumb-crossed:', ':snap:', ':finger-heart:']),
      NotoEmoji(char: '🤙', code: '1f919', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤙🏻', code: '1f919_1f3fb', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤙🏼', code: '1f919_1f3fc', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤙🏽', code: '1f919_1f3fd', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤙🏾', code: '1f919_1f3fe', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤙🏿', code: '1f919_1f3ff', tags: [':call-me-hand:']),
      NotoEmoji(char: '🤌', code: '1f90c', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤌🏻', code: '1f90c_1f3fb', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤌🏼', code: '1f90c_1f3fc', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤌🏽', code: '1f90c_1f3fd', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤌🏾', code: '1f90c_1f3fe', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤌🏿', code: '1f90c_1f3ff', tags: [':pinched-fingers:']),
      NotoEmoji(char: '🤏', code: '1f90f', tags: [':pinch:']),
      NotoEmoji(char: '🤏🏻', code: '1f90f_1f3fb', tags: [':pinch:']),
      NotoEmoji(char: '🤏🏼', code: '1f90f_1f3fc', tags: [':pinch:']),
      NotoEmoji(char: '🤏🏽', code: '1f90f_1f3fd', tags: [':pinch:']),
      NotoEmoji(char: '🤏🏾', code: '1f90f_1f3fe', tags: [':pinch:']),
      NotoEmoji(char: '🤏🏿', code: '1f90f_1f3ff', tags: [':pinch:']),
      NotoEmoji(char: '👌', code: '1f44c', tags: [':ok:']),
      NotoEmoji(char: '👌🏻', code: '1f44c_1f3fb', tags: [':ok:']),
      NotoEmoji(char: '👌🏼', code: '1f44c_1f3fc', tags: [':ok:']),
      NotoEmoji(char: '👌🏽', code: '1f44c_1f3fd', tags: [':ok:']),
      NotoEmoji(char: '👌🏾', code: '1f44c_1f3fe', tags: [':ok:']),
      NotoEmoji(char: '👌🏿', code: '1f44c_1f3ff', tags: [':ok:']),
      NotoEmoji(char: '🫵', code: '1faf5', tags: [':pointing:']),
      NotoEmoji(char: '🫵🏻', code: '1faf5_1f3fb', tags: [':pointing:']),
      NotoEmoji(char: '🫵🏼', code: '1faf5_1f3fc', tags: [':pointing:']),
      NotoEmoji(char: '🫵🏽', code: '1faf5_1f3fd', tags: [':pointing:']),
      NotoEmoji(char: '🫵🏾', code: '1faf5_1f3fe', tags: [':pointing:']),
      NotoEmoji(char: '🫵🏿', code: '1faf5_1f3ff', tags: [':pointing:']),
      NotoEmoji(char: '👉', code: '1f449', tags: [':point-right:']),
      NotoEmoji(char: '👉🏻', code: '1f449_1f3fb', tags: [':point-right:']),
      NotoEmoji(char: '👉🏼', code: '1f449_1f3fc', tags: [':point-right:']),
      NotoEmoji(char: '👉🏽', code: '1f449_1f3fd', tags: [':point-right:']),
      NotoEmoji(char: '👉🏾', code: '1f449_1f3fe', tags: [':point-right:']),
      NotoEmoji(char: '👉🏿', code: '1f449_1f3ff', tags: [':point-right:']),
      NotoEmoji(char: '👈', code: '1f448', tags: [':point-left:']),
      NotoEmoji(char: '👈🏻', code: '1f448_1f3fb', tags: [':point-left:']),
      NotoEmoji(char: '👈🏼', code: '1f448_1f3fc', tags: [':point-left:']),
      NotoEmoji(char: '👈🏽', code: '1f448_1f3fd', tags: [':point-left:']),
      NotoEmoji(char: '👈🏾', code: '1f448_1f3fe', tags: [':point-left:']),
      NotoEmoji(char: '👈🏿', code: '1f448_1f3ff', tags: [':point-left:']),
      NotoEmoji(char: '☝️', code: '261d_fe0f', tags: [':index-finger:']),
      NotoEmoji(char: '☝🏻', code: '261d_1f3fb', tags: [':index-finger:']),
      NotoEmoji(char: '☝🏼', code: '261d_1f3fc', tags: [':index-finger:']),
      NotoEmoji(char: '☝🏽', code: '261d_1f3fd', tags: [':index-finger:']),
      NotoEmoji(char: '☝🏾', code: '261d_1f3fe', tags: [':index-finger:']),
      NotoEmoji(char: '☝🏿', code: '261d_1f3ff', tags: [':index-finger:']),
      NotoEmoji(char: '👆', code: '1f446', tags: [':point-up:']),
      NotoEmoji(char: '👆🏻', code: '1f446_1f3fb', tags: [':point-up:']),
      NotoEmoji(char: '👆🏼', code: '1f446_1f3fc', tags: [':point-up:']),
      NotoEmoji(char: '👆🏽', code: '1f446_1f3fd', tags: [':point-up:']),
      NotoEmoji(char: '👆🏾', code: '1f446_1f3fe', tags: [':point-up:']),
      NotoEmoji(char: '👆🏿', code: '1f446_1f3ff', tags: [':point-up:']),
      NotoEmoji(char: '👇', code: '1f447', tags: [':point-down:']),
      NotoEmoji(char: '👇🏻', code: '1f447_1f3fb', tags: [':point-down:']),
      NotoEmoji(char: '👇🏼', code: '1f447_1f3fc', tags: [':point-down:']),
      NotoEmoji(char: '👇🏽', code: '1f447_1f3fd', tags: [':point-down:']),
      NotoEmoji(char: '👇🏾', code: '1f447_1f3fe', tags: [':point-down:']),
      NotoEmoji(char: '👇🏿', code: '1f447_1f3ff', tags: [':point-down:']),
      NotoEmoji(char: '🖕', code: '1f595', tags: [':middle-finger:']),
      NotoEmoji(char: '🖕🏻', code: '1f595_1f3fb', tags: [':middle-finger:']),
      NotoEmoji(char: '🖕🏼', code: '1f595_1f3fc', tags: [':middle-finger:']),
      NotoEmoji(char: '🖕🏽', code: '1f595_1f3fd', tags: [':middle-finger:']),
      NotoEmoji(char: '🖕🏾', code: '1f595_1f3fe', tags: [':middle-finger:']),
      NotoEmoji(char: '🖕🏿', code: '1f595_1f3ff', tags: [':middle-finger:']),
      NotoEmoji(char: '✍️', code: '270d_fe0f', tags: [':writing-hand:']),
      NotoEmoji(char: '✍🏻', code: '270d_1f3fb', tags: [':writing-hand:']),
      NotoEmoji(char: '✍🏼', code: '270d_1f3fc', tags: [':writing-hand:']),
      NotoEmoji(char: '✍🏽', code: '270d_1f3fd', tags: [':writing-hand:']),
      NotoEmoji(char: '✍🏾', code: '270d_1f3fe', tags: [':writing-hand:']),
      NotoEmoji(char: '✍🏿', code: '270d_1f3ff', tags: [':writing-hand:']),
      NotoEmoji(char: '🤳', code: '1f933', tags: [':selfie:']),
      NotoEmoji(char: '🤳🏻', code: '1f933_1f3fb', tags: [':selfie:']),
      NotoEmoji(char: '🤳🏼', code: '1f933_1f3fc', tags: [':selfie:']),
      NotoEmoji(char: '🤳🏽', code: '1f933_1f3fd', tags: [':selfie:']),
      NotoEmoji(char: '🤳🏾', code: '1f933_1f3fe', tags: [':selfie:']),
      NotoEmoji(char: '🤳🏿', code: '1f933_1f3ff', tags: [':selfie:']),
      NotoEmoji(char: '🙏', code: '1f64f', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '🙏🏻', code: '1f64f_1f3fb', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '🙏🏼', code: '1f64f_1f3fc', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '🙏🏽', code: '1f64f_1f3fd', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '🙏🏾', code: '1f64f_1f3fe', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '🙏🏿', code: '1f64f_1f3ff', tags: [':folded-hands:', ':please:', ':pray:', ':hope:', ':wish:', ':thank-you:', ':high-five:']),
      NotoEmoji(char: '💅', code: '1f485', tags: [':nail-care:']),
      NotoEmoji(char: '💅🏻', code: '1f485_1f3fb', tags: [':nail-care:']),
      NotoEmoji(char: '💅🏼', code: '1f485_1f3fc', tags: [':nail-care:']),
      NotoEmoji(char: '💅🏽', code: '1f485_1f3fd', tags: [':nail-care:']),
      NotoEmoji(char: '💅🏾', code: '1f485_1f3fe', tags: [':nail-care:']),
      NotoEmoji(char: '💅🏿', code: '1f485_1f3ff', tags: [':nail-care:']),
      NotoEmoji(char: '🤝', code: '1f91d', tags: [':handshake:']),
      NotoEmoji(char: '🤝🏻', code: '1f91d_1f3fb', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏻‍🫲🏼', code: '1faf1_1f3fb_200d_1faf2_1f3fc', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏻‍🫲🏽', code: '1faf1_1f3fb_200d_1faf2_1f3fd', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏻‍🫲🏾', code: '1faf1_1f3fb_200d_1faf2_1f3fe', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏻‍🫲🏿', code: '1faf1_1f3fb_200d_1faf2_1f3ff', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏼‍🫲🏻', code: '1faf1_1f3fc_200d_1faf2_1f3fb', tags: [':handshake:']),
      NotoEmoji(char: '🤝🏼', code: '1f91d_1f3fc', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏼‍🫲🏽', code: '1faf1_1f3fc_200d_1faf2_1f3fd', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏼‍🫲🏾', code: '1faf1_1f3fc_200d_1faf2_1f3fe', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏼‍🫲🏿', code: '1faf1_1f3fc_200d_1faf2_1f3ff', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏽‍🫲🏻', code: '1faf1_1f3fd_200d_1faf2_1f3fb', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏽‍🫲🏼', code: '1faf1_1f3fd_200d_1faf2_1f3fc', tags: [':handshake:']),
      NotoEmoji(char: '🤝🏽', code: '1f91d_1f3fd', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏽‍🫲🏾', code: '1faf1_1f3fd_200d_1faf2_1f3fe', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏽‍🫲🏿', code: '1faf1_1f3fd_200d_1faf2_1f3ff', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏾‍🫲🏻', code: '1faf1_1f3fe_200d_1faf2_1f3fb', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏾‍🫲🏼', code: '1faf1_1f3fe_200d_1faf2_1f3fc', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏾‍🫲🏽', code: '1faf1_1f3fe_200d_1faf2_1f3fd', tags: [':handshake:']),
      NotoEmoji(char: '🤝🏾', code: '1f91d_1f3fe', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏾‍🫲🏿', code: '1faf1_1f3fe_200d_1faf2_1f3ff', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏿‍🫲🏻', code: '1faf1_1f3ff_200d_1faf2_1f3fb', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏿‍🫲🏼', code: '1faf1_1f3ff_200d_1faf2_1f3fc', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏿‍🫲🏽', code: '1faf1_1f3ff_200d_1faf2_1f3fd', tags: [':handshake:']),
      NotoEmoji(char: '🫱🏿‍🫲🏾', code: '1faf1_1f3ff_200d_1faf2_1f3fe', tags: [':handshake:']),
      NotoEmoji(char: '🤝🏿', code: '1f91d_1f3ff', tags: [':handshake:']),
    ],
    'Animals': [
      NotoEmoji(char: '💐', code: '1f490', tags: [':bouquet:', ':flowers:']),
      NotoEmoji(char: '🌹', code: '1f339', tags: [':rose:']),
      NotoEmoji(char: '🥀', code: '1f940', tags: [':wilted-flower:']),
      NotoEmoji(char: '🌷', code: '1f337', tags: [':tulip:']),
      NotoEmoji(char: '🪷', code: '1fab7', tags: [':lotus:']),
      NotoEmoji(char: '🌸', code: '1f338', tags: [':cherry-blossom:']),
      NotoEmoji(char: '🪻', code: '1fabb', tags: [':hyacinth:']),
      NotoEmoji(char: '🌼', code: '1f33c', tags: [':blossom:']),
      NotoEmoji(char: '🍂', code: '1f342', tags: [':fallen-leaf:']),
      NotoEmoji(char: '🍁', code: '1f341', tags: [':maple-leaf:']),
      NotoEmoji(char: '🍄', code: '1f344', tags: [':mushroom:']),
      NotoEmoji(char: '🌿', code: '1f33f', tags: [':herb:']),
      NotoEmoji(char: '🌱', code: '1f331', tags: [':plant:', ':seed:']),
      NotoEmoji(char: '🍃', code: '1f343', tags: [':leaves:']),
      NotoEmoji(char: '🍀', code: '1f340', tags: [':luck:', ':four-leaf-clover:']),
      NotoEmoji(char: '🌵', code: '1f335', tags: [':cactus:']),
      NotoEmoji(char: '🪾', code: '1fabe', tags: [':leafless-tree:']),
      NotoEmoji(char: '🌲', code: '1f332', tags: [':evergreen-tree:']),
      NotoEmoji(char: '🪨', code: '1faa8', tags: [':rock:']),
      NotoEmoji(char: '🛘', code: '1f6d8', tags: [':debris:', ':landslide:']),
      NotoEmoji(char: '🌋', code: '1f30b', tags: [':volcano:']),
      NotoEmoji(char: '🏞️', code: '1f3de_fe0f', tags: [':national-park:']),
      NotoEmoji(char: '🌅', code: '1f305', tags: [':sunrise:']),
      NotoEmoji(char: '🌄', code: '1f304', tags: [':sunrise-over-mountains:']),
      NotoEmoji(char: '🌊', code: '1f30a', tags: [':ocean:']),
      NotoEmoji(char: '🌬️', code: '1f32c_fe0f', tags: [':wind-face:']),
      NotoEmoji(char: '❄️', code: '2744_fe0f', tags: [':snowflake:', ':winter:', ':cold:']),
      NotoEmoji(char: '🌀', code: '1f300', tags: [':cyclone:']),
      NotoEmoji(char: '🌪️', code: '1f32a_fe0f', tags: [':tornado:']),
      NotoEmoji(char: '🌈', code: '1f308', tags: [':rainbow:']),
      NotoEmoji(char: '💧', code: '1f4a7', tags: [':droplet:']),
      NotoEmoji(char: '☁️', code: '2601_fe0f', tags: [':cloud:']),
      NotoEmoji(char: '🌧️', code: '1f327_fe0f', tags: [':rain-cloud:']),
      NotoEmoji(char: '🌩️', code: '1f329_fe0f', tags: [':cloud-with-lightning:']),
      NotoEmoji(char: '⛅', code: '26c5', tags: [':partly-sunny:']),
      NotoEmoji(char: '🪐', code: '1fa90', tags: [':ringed-planet:']),
      NotoEmoji(char: '🌍', code: '1f30d', tags: [':globe-showing-Europe-Africa:']),
      NotoEmoji(char: '🌎', code: '1f30e', tags: [':globe-showing-Americas:']),
      NotoEmoji(char: '🌏', code: '1f30f', tags: [':globe-showing-Asia-Australia:']),
      NotoEmoji(char: '🌌', code: '1f30c', tags: [':milky-way:']),
      NotoEmoji(char: '☄️', code: '2604_fe0f', tags: [':comet:']),
      NotoEmoji(char: '🦁', code: '1f981', tags: [':lion-face:']),
      NotoEmoji(char: '🐺', code: '1f43a', tags: [':wolf:']),
      NotoEmoji(char: '🐻', code: '1f43b', tags: [':bear-face:']),
      NotoEmoji(char: '🐼', code: '1f43c', tags: [':panda:']),
      NotoEmoji(char: '🦊', code: '1f98a', tags: [':fox-face:']),
      NotoEmoji(char: '🐮', code: '1f42e', tags: [':cow-face:']),
      NotoEmoji(char: '🦄', code: '1f984', tags: [':unicorn:']),
      NotoEmoji(char: '🦎', code: '1f98e', tags: [':lizard:']),
      NotoEmoji(char: '🐉', code: '1f409', tags: [':dragon:']),
      NotoEmoji(char: '🦖', code: '1f996', tags: [':t-rex:']),
      NotoEmoji(char: '🦕', code: '1f995', tags: [':dinosaur:']),
      NotoEmoji(char: '🐢', code: '1f422', tags: [':turtle:']),
      NotoEmoji(char: '🐊', code: '1f40a', tags: [':crocodile:']),
      NotoEmoji(char: '🐍', code: '1f40d', tags: [':snake:']),
      NotoEmoji(char: '🐸', code: '1f438', tags: [':frog:']),
      NotoEmoji(char: '🐇', code: '1f407', tags: [':rabbit:']),
      NotoEmoji(char: '🐀', code: '1f400', tags: [':rat:']),
      NotoEmoji(char: '🐩', code: '1f429', tags: [':poodle:']),
      NotoEmoji(char: '🐕', code: '1f415', tags: [':dog:']),
      NotoEmoji(char: '🦮', code: '1f9ae', tags: [':guide-dog:']),
      NotoEmoji(char: '🐕‍🦺', code: '1f415_200d_1f9ba', tags: [':service-dog:']),
      NotoEmoji(char: '🐖', code: '1f416', tags: [':pig:']),
      NotoEmoji(char: '🐎', code: '1f40e', tags: [':racehorse:']),
      NotoEmoji(char: '🫏', code: '1facf', tags: [':donkey:']),
      NotoEmoji(char: '🐂', code: '1f402', tags: [':ox:']),
      NotoEmoji(char: '🐐', code: '1f410', tags: [':goat:']),
      NotoEmoji(char: '🦥', code: '1f9a5', tags: [':sloth:']),
      NotoEmoji(char: '🦘', code: '1f998', tags: [':kangaroo:']),
      NotoEmoji(char: '🐅', code: '1f405', tags: [':tiger:']),
      NotoEmoji(char: '🐒', code: '1f412', tags: [':monkey:']),
      NotoEmoji(char: '🦍', code: '1f98d', tags: [':gorilla:']),
      NotoEmoji(char: '🦧', code: '1f9a7', tags: [':orangutan:']),
      NotoEmoji(char: '🐿️', code: '1f43f_fe0f', tags: [':chipmunk:']),
      NotoEmoji(char: '🦝', code: '1f99d', tags: [':raccoon:']),
      NotoEmoji(char: '🦔', code: '1f994', tags: [':hedgehog:']),
      NotoEmoji(char: '🦦', code: '1f9a6', tags: [':otter:']),
      NotoEmoji(char: '🦇', code: '1f987', tags: [':bat:']),
      NotoEmoji(char: '🐦', code: '1f426', tags: [':bird:']),
      NotoEmoji(char: '🐦‍⬛', code: '1f426_200d_2b1b', tags: [':black-bird:']),
      NotoEmoji(char: '🐓', code: '1f413', tags: [':rooster:']),
      NotoEmoji(char: '🐣', code: '1f423', tags: [':hatching-chick:']),
      NotoEmoji(char: '🐤', code: '1f424', tags: [':baby-chick:']),
      NotoEmoji(char: '🐥', code: '1f425', tags: [':hatched-chick:']),
      NotoEmoji(char: '🦅', code: '1f985', tags: [':eagle:']),
      NotoEmoji(char: '🦉', code: '1f989', tags: [':owl:']),
      NotoEmoji(char: '🕊️', code: '1f54a_fe0f', tags: [':peace:', ':dove:']),
      NotoEmoji(char: '🪿', code: '1fabf', tags: [':goose:']),
      NotoEmoji(char: '🦩', code: '1f9a9', tags: [':flamingo:']),
      NotoEmoji(char: '🦚', code: '1f99a', tags: [':peacock:']),
      NotoEmoji(char: '🐦‍🔥', code: '1f426_200d_1f525', tags: [':phoenix:']),
      NotoEmoji(char: '🐧', code: '1f427', tags: [':penguin:']),
      NotoEmoji(char: '🦭', code: '1f9ad', tags: [':seal:']),
      NotoEmoji(char: '🦈', code: '1f988', tags: [':shark:']),
      NotoEmoji(char: '🫍', code: '1facd', tags: [':orca:']),
      NotoEmoji(char: '🐬', code: '1f42c', tags: [':dolphin:']),
      NotoEmoji(char: '🐳', code: '1f433', tags: [':whale:']),
      NotoEmoji(char: '🐟', code: '1f41f', tags: [':fish:']),
      NotoEmoji(char: '🐡', code: '1f421', tags: [':blowfish:']),
      NotoEmoji(char: '🦞', code: '1f99e', tags: [':lobster:']),
      NotoEmoji(char: '🦀', code: '1f980', tags: [':crab:']),
      NotoEmoji(char: '🐙', code: '1f419', tags: [':octopus:']),
      NotoEmoji(char: '🪼', code: '1fabc', tags: [':jellyfish:']),
      NotoEmoji(char: '🫧', code: '1fae7', tags: [':bubbles:']),
      NotoEmoji(char: '🦂', code: '1f982', tags: [':scorpion:']),
      NotoEmoji(char: '🕷️', code: '1f577_fe0f', tags: [':spider:']),
      NotoEmoji(char: '🐌', code: '1f40c', tags: [':snail:']),
      NotoEmoji(char: '🐜', code: '1f41c', tags: [':ant:']),
      NotoEmoji(char: '🦗', code: '1f997', tags: [':cricket:']),
      NotoEmoji(char: '🦟', code: '1f99f', tags: [':mosquito:']),
      NotoEmoji(char: '🪳', code: '1fab3', tags: [':cockroach:']),
      NotoEmoji(char: '🪰', code: '1fab0', tags: [':fly:']),
      NotoEmoji(char: '🐝', code: '1f41d', tags: [':bee:']),
      NotoEmoji(char: '🐞', code: '1f41e', tags: [':lady-bug:']),
      NotoEmoji(char: '🦋', code: '1f98b', tags: [':butterfly:']),
      NotoEmoji(char: '🐛', code: '1f41b', tags: [':bug:']),
      NotoEmoji(char: '🪱', code: '1fab1', tags: [':worm:']),
      NotoEmoji(char: '🐾', code: '1f43e', tags: [':paw prints:']),
    ],
    'Food': [
      NotoEmoji(char: '🍓', code: '1f353', tags: [':strawberry:']),
      NotoEmoji(char: '🍒', code: '1f352', tags: [':cherries:']),
      NotoEmoji(char: '🍎', code: '1f34e', tags: [':red-apple:']),
      NotoEmoji(char: '🍅', code: '1f345', tags: [':tomato:']),
      NotoEmoji(char: '🍉', code: '1f349', tags: [':watermelon:']),
      NotoEmoji(char: '🍊', code: '1f34a', tags: [':tangerine:', ':orange:', ':mandarin:']),
      NotoEmoji(char: '🥕', code: '1f955', tags: [':carrot:']),
      NotoEmoji(char: '🥭', code: '1f96d', tags: [':mango:']),
      NotoEmoji(char: '🍍', code: '1f34d', tags: [':pineapple:']),
      NotoEmoji(char: '🌽', code: '1f33d', tags: [':ear-of-corn:']),
      NotoEmoji(char: '🍋', code: '1f34b', tags: [':lemon:']),
      NotoEmoji(char: '🍈', code: '1f348', tags: [':melon:']),
      NotoEmoji(char: '🍐', code: '1f350', tags: [':pear:']),
      NotoEmoji(char: '🫛', code: '1fadb', tags: [':pea-pod:']),
      NotoEmoji(char: '🥬', code: '1f96c', tags: [':leafy-green:']),
      NotoEmoji(char: '🫑', code: '1fad1', tags: [':bell-pepper:']),
      NotoEmoji(char: '🥝', code: '1f95d', tags: [':kiwi-fruit:']),
      NotoEmoji(char: '🥑', code: '1f951', tags: [':avocado:']),
      NotoEmoji(char: '🥦', code: '1f966', tags: [':broccoli:']),
      NotoEmoji(char: '🥒', code: '1f952', tags: [':cucumber:']),
      NotoEmoji(char: '🫐', code: '1fad0', tags: [':blueberries:']),
      NotoEmoji(char: '🍇', code: '1f347', tags: [':grapes:']),
      NotoEmoji(char: '🫜', code: '1fadc', tags: [':root-vegetable:', ':beet:', ':turnip:']),
      NotoEmoji(char: '🥔', code: '1f954', tags: [':potato:']),
      NotoEmoji(char: '🧅', code: '1f9c5', tags: [':onion:']),
      NotoEmoji(char: '🫚', code: '1fada', tags: [':ginger:']),
      NotoEmoji(char: '🧄', code: '1f9c4', tags: [':garlic:']),
      NotoEmoji(char: '🫘', code: '1fad8', tags: [':beans:']),
      NotoEmoji(char: '🍞', code: '1f35e', tags: [':bread:']),
      NotoEmoji(char: '🥞', code: '1f95e', tags: [':pancakes:']),
      NotoEmoji(char: '🍳', code: '1f373', tags: [':cooking:']),
      NotoEmoji(char: '🧀', code: '1f9c0', tags: [':cheese-wedge:']),
      NotoEmoji(char: '🥓', code: '1f953', tags: [':bacon:']),
      NotoEmoji(char: '🍗', code: '1f357', tags: [':poultry-leg:']),
      NotoEmoji(char: '🍔', code: '1f354', tags: [':hamburger:']),
      NotoEmoji(char: '🌭', code: '1f32d', tags: [':hot-dog:']),
      NotoEmoji(char: '🥨', code: '1f968', tags: [':pretzel:']),
      NotoEmoji(char: '🍕', code: '1f355', tags: [':pizza:']),
      NotoEmoji(char: '🌮', code: '1f32e', tags: [':taco:']),
      NotoEmoji(char: '🌯', code: '1f32f', tags: [':burrito:']),
      NotoEmoji(char: '🍝', code: '1f35d', tags: [':spaghetti:']),
      NotoEmoji(char: '🥗', code: '1f957', tags: [':green-salad:']),
      NotoEmoji(char: '🍜', code: '1f35c', tags: [':steaming-bowl:']),
      NotoEmoji(char: '🍢', code: '1f362', tags: [':oden:']),
      NotoEmoji(char: '🍡', code: '1f361', tags: [':dango:']),
      NotoEmoji(char: '🍨', code: '1f368', tags: [':ice-cream:']),
      NotoEmoji(char: '🍦', code: '1f366', tags: [':soft-ice-cream:']),
      NotoEmoji(char: '🥧', code: '1f967', tags: [':pie:']),
      NotoEmoji(char: '🍩', code: '1f369', tags: [':doughnut:']),
      NotoEmoji(char: '🍪', code: '1f36a', tags: [':cookie:']),
      NotoEmoji(char: '🧂', code: '1f9c2', tags: [':salt:']),
      NotoEmoji(char: '🍿', code: '1f37f', tags: [':popcorn:']),
      NotoEmoji(char: '🧋', code: '1f9cb', tags: [':bubble-tea:', ':milk-tea:']),
      NotoEmoji(char: '🧃', code: '1f9c3', tags: [':beverage-box:']),
      NotoEmoji(char: '🍼', code: '1f37c', tags: [':baby-bottle:']),
      NotoEmoji(char: '🍵', code: '1f375', tags: [':teacup-without-handle:']),
      NotoEmoji(char: '☕', code: '2615', tags: [':hot-beverage:']),
      NotoEmoji(char: '🫖', code: '1fad6', tags: [':teapot:']),
      NotoEmoji(char: '🧉', code: '1f9c9', tags: [':mate:']),
      NotoEmoji(char: '🍻', code: '1f37b', tags: [':clinking-beer-mugs:']),
      NotoEmoji(char: '🥂', code: '1f942', tags: [':clinking-glasses:']),
      NotoEmoji(char: '🍾', code: '1f37e', tags: [':bottle-with-popping-cork:']),
      NotoEmoji(char: '🍷', code: '1f377', tags: [':wine-glass:']),
      NotoEmoji(char: '🫗', code: '1fad7', tags: [':pour:']),
      NotoEmoji(char: '🍹', code: '1f379', tags: [':tropical-drink:']),
      NotoEmoji(char: '🥢', code: '1f962', tags: [':chopsticks:']),
      NotoEmoji(char: '🍽️', code: '1f37d_fe0f', tags: [':fork-and-knife-with-plate:']),
    ],
    'Activities': [
      NotoEmoji(char: '🎈', code: '1f388', tags: [':balloon:']),
      NotoEmoji(char: '🎂', code: '1f382', tags: [':birthday-cake:']),
      NotoEmoji(char: '🎁', code: '1f381', tags: [':wrapped-gift:']),
      NotoEmoji(char: '🎆', code: '1f386', tags: [':fireworks:']),
      NotoEmoji(char: '🪔', code: '1fa94', tags: [':diya-lamp:']),
      NotoEmoji(char: '🪅', code: '1fa85', tags: [':piñata:']),
      NotoEmoji(char: '🪩', code: '1faa9', tags: [':mirror-ball:', ':disco-ball:']),
      NotoEmoji(char: '🥇', code: '1f947', tags: [':gold-medal:', ':1st-place-medal:']),
      NotoEmoji(char: '🥈', code: '1f948', tags: [':silver-medal:', ':2nd-place-medal:']),
      NotoEmoji(char: '🥉', code: '1f949', tags: [':bronze-medal:', ':3rd-place-medal:']),
      NotoEmoji(char: '🏆', code: '1f3c6', tags: [':trophy:']),
      NotoEmoji(char: '⚽', code: '26bd', tags: [':soccer-ball:']),
      NotoEmoji(char: '⚾', code: '26be', tags: [':baseball:']),
      NotoEmoji(char: '🥎', code: '1f94e', tags: [':softball:']),
      NotoEmoji(char: '🏀', code: '1f3c0', tags: [':basketball:']),
      NotoEmoji(char: '🏉', code: '1f3c9', tags: [':rugby-football:']),
      NotoEmoji(char: '🎾', code: '1f3be', tags: [':tennis:']),
      NotoEmoji(char: '🏸', code: '1f3f8', tags: [':badminton:']),
      NotoEmoji(char: '🥍', code: '1f94d', tags: [':lacrosse:']),
      NotoEmoji(char: '🏏', code: '1f3cf', tags: [':cricket-game:']),
      NotoEmoji(char: '🏑', code: '1f3d1', tags: [':field-hockey:']),
      NotoEmoji(char: '🏒', code: '1f3d2', tags: [':ice-hockey:']),
      NotoEmoji(char: '🎿', code: '1f3bf', tags: [':skis:']),
      NotoEmoji(char: '⛸️', code: '26f8_fe0f', tags: [':ice-skate:']),
      NotoEmoji(char: '🛼', code: '1f6fc', tags: [':roller-skates:']),
      NotoEmoji(char: '🩰', code: '1fa70', tags: [':ballet-shoes:']),
      NotoEmoji(char: '🛹', code: '1f6f9', tags: [':skateboard:']),
      NotoEmoji(char: '⛳', code: '26f3', tags: [':flag-in-hole:']),
      NotoEmoji(char: '🎯', code: '1f3af', tags: [':direct-hit:', ':target:']),
      NotoEmoji(char: '🥏', code: '1f94f', tags: [':flying-disc:']),
      NotoEmoji(char: '🪃', code: '1fa83', tags: [':boomerang:']),
      NotoEmoji(char: '🪁', code: '1fa81', tags: [':kite:']),
      NotoEmoji(char: '🎣', code: '1f3a3', tags: [':fishing-pole:']),
      NotoEmoji(char: '🥋', code: '1f94b', tags: [':martial-arts-uniform:']),
      NotoEmoji(char: '🎱', code: '1f3b1', tags: [':8-ball:']),
      NotoEmoji(char: '🏓', code: '1f3d3', tags: [':ping-pong:']),
      NotoEmoji(char: '🎳', code: '1f3b3', tags: [':bowling:']),
      NotoEmoji(char: '♟️', code: '265f_fe0f', tags: [':chess-pawn:']),
      NotoEmoji(char: '🎲', code: '1f3b2', tags: [':die:']),
      NotoEmoji(char: '🎰', code: '1f3b0', tags: [':slot-machine:']),
      NotoEmoji(char: '🪄', code: '1fa84', tags: [':wand:']),
      NotoEmoji(char: '📷', code: '1f4f7', tags: [':camera:']),
      NotoEmoji(char: '📸', code: '1f4f8', tags: [':camera-flash:']),
      NotoEmoji(char: '🫟', code: '1fadf', tags: [':splatter:']),
      NotoEmoji(char: '🎷', code: '1f3b7', tags: [':saxophone:']),
      NotoEmoji(char: '🎺', code: '1f3ba', tags: [':trumpet:']),
      NotoEmoji(char: '🪊', code: '1fa8a', tags: [':trombone:']),
      NotoEmoji(char: '🎸', code: '1f3b8', tags: [':guitar:']),
      NotoEmoji(char: '🪕', code: '1fa95', tags: [':banjo:']),
      NotoEmoji(char: '🎻', code: '1f3bb', tags: [':violin:']),
      NotoEmoji(char: '🪉', code: '1fa89', tags: [':harp:']),
      NotoEmoji(char: '🥁', code: '1f941', tags: [':drum:']),
      NotoEmoji(char: '🪇', code: '1fa87', tags: [':maracas:']),
      NotoEmoji(char: '📺', code: '1f4fa', tags: [':television:']),
      NotoEmoji(char: '🎞️', code: '1f39e_fe0f', tags: [':film:']),
      NotoEmoji(char: '🎬', code: '1f3ac', tags: [':clapper:']),
      NotoEmoji(char: '🎭', code: '1f3ad', tags: [':performing-arts:']),
      NotoEmoji(char: '🎟️', code: '1f39f_fe0f', tags: [':admission-tickets:']),
    ],
    'Travel': [
      NotoEmoji(char: '🛑', code: '1f6d1', tags: [':stop-sign:']),
      NotoEmoji(char: '🚧', code: '1f6a7', tags: [':construction:']),
      NotoEmoji(char: '🚨', code: '1f6a8', tags: [':police-car-light:']),
      NotoEmoji(char: '⛽', code: '26fd', tags: [':fuel-pump:']),
      NotoEmoji(char: '🛟', code: '1f6df', tags: [':ring-buoy:']),
      NotoEmoji(char: '⚓', code: '2693', tags: [':anchor:']),
      NotoEmoji(char: '🚦', code: '1f6a6', tags: [':vertical-traffic-light:']),
      NotoEmoji(char: '🚲', code: '1f6b2', tags: [':bicycle:']),
      NotoEmoji(char: '🏍️', code: '1f3cd_fe0f', tags: [':motorcycle:']),
      NotoEmoji(char: '🚗', code: '1f697', tags: [':automobile:']),
      NotoEmoji(char: '🚚', code: '1f69a', tags: [':delivery-truck:']),
      NotoEmoji(char: '🚜', code: '1f69c', tags: [':tractor:']),
      NotoEmoji(char: '🏎️', code: '1f3ce_fe0f', tags: [':racing-car:']),
      NotoEmoji(char: '🚕', code: '1f695', tags: [':taxi:']),
      NotoEmoji(char: '🚌', code: '1f68c', tags: [':bus:']),
      NotoEmoji(char: '🚂', code: '1f682', tags: [':locomotive:']),
      NotoEmoji(char: '⛵', code: '26f5', tags: [':sailboat:']),
      NotoEmoji(char: '🛶', code: '1f6f6', tags: [':canoe:']),
      NotoEmoji(char: '🛸', code: '1f6f8', tags: [':flying-saucer:']),
      NotoEmoji(char: '🚀', code: '1f680', tags: [':rocket:']),
      NotoEmoji(char: '✈️', code: '2708_fe0f', tags: [':airplane:']),
      NotoEmoji(char: '🛫', code: '1f6eb', tags: [':airplane-departure:']),
      NotoEmoji(char: '🛬', code: '1f6ec', tags: [':airplane-arrival:']),
      NotoEmoji(char: '🎢', code: '1f3a2', tags: [':roller-coaster:']),
      NotoEmoji(char: '🎡', code: '1f3a1', tags: [':ferris-wheel:']),
      NotoEmoji(char: '🎠', code: '1f3a0', tags: [':carousel-horse:']),
      NotoEmoji(char: '🗿', code: '1f5ff', tags: [':moai:']),
      NotoEmoji(char: '🏚️', code: '1f3da_fe0f', tags: [':derelict-house:']),
      NotoEmoji(char: '🏠', code: '1f3e0', tags: [':house:']),
      NotoEmoji(char: '🏕️', code: '1f3d5_fe0f', tags: [':camping:']),
      NotoEmoji(char: '🌇', code: '1f307', tags: [':sunset:']),
    ],
    'Objects': [
      NotoEmoji(char: '📟', code: '1f4df', tags: [':pager:']),
      NotoEmoji(char: '🔌', code: '1f50c', tags: [':electric-plug:']),
      NotoEmoji(char: '🔋', code: '1f50b', tags: [':battery-full:']),
      NotoEmoji(char: '🪫', code: '1faab', tags: [':battery-low:']),
      NotoEmoji(char: '💿', code: '1f4bf', tags: [':optical-disk:']),
      NotoEmoji(char: '💻', code: '1f4bb', tags: [':laptop-computer:']),
      NotoEmoji(char: '🖨️', code: '1f5a8_fe0f', tags: [':printer:']),
      NotoEmoji(char: '🪎', code: '1fa8e', tags: [':treasure:']),
      NotoEmoji(char: '🪙', code: '1fa99', tags: [':coin:']),
      NotoEmoji(char: '💎', code: '1f48e', tags: [':gem-stone:']),
      NotoEmoji(char: '💸', code: '1f4b8', tags: [':money-with-wings:']),
      NotoEmoji(char: '⚖️', code: '2696_fe0f', tags: [':balance-scale:']),
      NotoEmoji(char: '🛒', code: '1f6d2', tags: [':shopping-cart:']),
      NotoEmoji(char: '💡', code: '1f4a1', tags: [':light-bulb:']),
      NotoEmoji(char: '🧹', code: '1f9f9', tags: [':broom:']),
      NotoEmoji(char: '🧦', code: '1f9e6', tags: [':socks:']),
      NotoEmoji(char: '🎓', code: '1f393', tags: [':graduation-cap:']),
      NotoEmoji(char: '👑', code: '1f451', tags: [':crown:']),
      NotoEmoji(char: '💍', code: '1f48d', tags: [':ring:']),
      NotoEmoji(char: '🪭', code: '1faad', tags: [':fan:']),
      NotoEmoji(char: '☂️', code: '2602_fe0f', tags: [':umbrella:']),
      NotoEmoji(char: '👠', code: '1f460', tags: [':high-heeled-shoe:']),
      NotoEmoji(char: '👟', code: '1f45f', tags: [':running-shoe:']),
      NotoEmoji(char: '🌡️', code: '1f321_fe0f', tags: [':thermometer:']),
      NotoEmoji(char: '🩺', code: '1fa7a', tags: [':stethoscope:']),
      NotoEmoji(char: '🛠️', code: '1f6e0_fe0f', tags: [':hammer-and-wrench:']),
      NotoEmoji(char: '🪏', code: '1fa8f', tags: [':shovel:', ':dig:']),
      NotoEmoji(char: '⚙️', code: '2699_fe0f', tags: [':gear:']),
      NotoEmoji(char: '⛓️‍💥', code: '26d3_fe0f_200d_1f4a5', tags: [':broken-chain:']),
      NotoEmoji(char: '⛓️', code: '26d3_fe0f', tags: [':chains:']),
      NotoEmoji(char: '🖇️', code: '1f587_fe0f', tags: [':linked-paperclips:']),
      NotoEmoji(char: '✂️', code: '2702_fe0f', tags: [':scissors:']),
      NotoEmoji(char: '✏️', code: '270f_fe0f', tags: [':pencil:']),
      NotoEmoji(char: '📚', code: '1f4da', tags: [':books:']),
      NotoEmoji(char: '📊', code: '1f4ca', tags: [':bar-chart:']),
      NotoEmoji(char: '📈', code: '1f4c8', tags: [':chart-increasing:']),
      NotoEmoji(char: '📉', code: '1f4c9', tags: [':chart-decreasing:']),
      NotoEmoji(char: '🗑️', code: '1f5d1_fe0f', tags: [':wastebasket:']),
      NotoEmoji(char: '📦', code: '1f4e6', tags: [':package:']),
      NotoEmoji(char: '🗳️', code: '1f5f3_fe0f', tags: [':ballot-box:']),
      NotoEmoji(char: '⏰', code: '23f0', tags: [':alarm-clock:']),
      NotoEmoji(char: '⌛', code: '231b', tags: [':hourglass-done:']),
      NotoEmoji(char: '⏳', code: '23f3', tags: [':hourglass-not-done:']),
      NotoEmoji(char: '🛎️', code: '1f6ce_fe0f', tags: [':bellhop-bell:']),
      NotoEmoji(char: '🔔', code: '1f514', tags: [':bell:']),
      NotoEmoji(char: '📣', code: '1f4e3', tags: [':megaphone:']),
      NotoEmoji(char: '🔎', code: '1f50e', tags: [':magnifying-glass-tilted-right:']),
      NotoEmoji(char: '🔮', code: '1f52e', tags: [':crystal-ball:']),
      NotoEmoji(char: '💣', code: '1f4a3', tags: [':bomb:']),
      NotoEmoji(char: '🪤', code: '1faa4', tags: [':mouse-trap:']),
      NotoEmoji(char: '🔒', code: '1f512', tags: [':locked:']),
    ],
    'Symbols': [
      NotoEmoji(char: '♠️', code: '2660_fe0f', tags: [':spade:']),
      NotoEmoji(char: '♈', code: '2648', tags: [':Aries:']),
      NotoEmoji(char: '♉', code: '2649', tags: [':Taurus:']),
      NotoEmoji(char: '♊', code: '264a', tags: [':Gemini:']),
      NotoEmoji(char: '♋', code: '264b', tags: [':Cancer:']),
      NotoEmoji(char: '♌', code: '264c', tags: [':Leo:']),
      NotoEmoji(char: '♍', code: '264d', tags: [':Virgo:']),
      NotoEmoji(char: '♎', code: '264e', tags: [':Libra:']),
      NotoEmoji(char: '♏', code: '264f', tags: [':Scorpio:']),
      NotoEmoji(char: '♐', code: '2650', tags: [':Sagittarius:']),
      NotoEmoji(char: '♑', code: '2651', tags: [':Capricorn:']),
      NotoEmoji(char: '♒', code: '2652', tags: [':Aquarius:']),
      NotoEmoji(char: '♓', code: '2653', tags: [':Pisces:']),
      NotoEmoji(char: '⛎', code: '26ce', tags: [':Ophiuchus:']),
      NotoEmoji(char: '🗯️', code: '1f5ef_fe0f', tags: [':anger-bubble:']),
      NotoEmoji(char: '💬', code: '1f4ac', tags: [':speech-bubble:']),
      NotoEmoji(char: '❗', code: '2757', tags: [':exclamation:', ':exclamation-mark:']),
      NotoEmoji(char: '❓', code: '2753', tags: [':question:', ':question-mark:', ':?:']),
      NotoEmoji(char: '⁉️', code: '2049_fe0f', tags: [':exclamation-question-mark:', ':!?:']),
      NotoEmoji(char: '‼️', code: '203c_fe0f', tags: [':exclamation-double:', ':!!:']),
      NotoEmoji(char: '❌', code: '274c', tags: [':cross-mark:', ':x:']),
      NotoEmoji(char: '🆘', code: '1f198', tags: [':sos:']),
      NotoEmoji(char: '♨️', code: '2668_fe0f', tags: [':hot-springs:']),
      NotoEmoji(char: '📴', code: '1f4f4', tags: [':phone-off:']),
      NotoEmoji(char: '☢️', code: '2622_fe0f', tags: [':radioactive:']),
      NotoEmoji(char: '☣️', code: '2623_fe0f', tags: [':biohazard:']),
      NotoEmoji(char: '⚠️', code: '26a0_fe0f', tags: [':warning:']),
      NotoEmoji(char: '✅', code: '2705', tags: [':check-mark:', ':check-mark-green:']),
      NotoEmoji(char: '🆕', code: '1f195', tags: [':new:']),
      NotoEmoji(char: '🆓', code: '1f193', tags: [':free:']),
      NotoEmoji(char: '🆙', code: '1f199', tags: [':up!:']),
      NotoEmoji(char: '🆗', code: '1f197', tags: [':ok-button:']),
      NotoEmoji(char: '🆒', code: '1f192', tags: [':cool:']),
      NotoEmoji(char: '🚮', code: '1f6ae', tags: [':litter:']),
      NotoEmoji(char: '☮️', code: '262e_fe0f', tags: [':peace-symbol:']),
      NotoEmoji(char: '☯️', code: '262f_fe0f', tags: [':yin-yang:']),
      NotoEmoji(char: '♾️', code: '267e_fe0f', tags: [':infinity:']),
      NotoEmoji(char: '🎶', code: '1f3b6', tags: [':musical-notes:']),
      NotoEmoji(char: '➕', code: '2795', tags: [':plus-sign:', ':+:']),
      NotoEmoji(char: '©️', code: 'a9_fe0f', tags: [':copyright:']),
      NotoEmoji(char: '®️', code: 'ae_fe0f', tags: [':registered:']),
      NotoEmoji(char: '™️', code: '2122_fe0f', tags: [':trade-mark:']),
    ],
    'People': [
      NotoEmoji(char: '🪂', code: '1fa82', tags: [':parachute:']),
      NotoEmoji(char: '🫈', code: '1fac8', tags: [':hairy-creature:']),
      NotoEmoji(char: '💃', code: '1f483', tags: [':dancer-woman:']),
      NotoEmoji(char: '💃🏻', code: '1f483_1f3fb', tags: [':dancer-woman:']),
      NotoEmoji(char: '💃🏼', code: '1f483_1f3fc', tags: [':dancer-woman:']),
      NotoEmoji(char: '💃🏽', code: '1f483_1f3fd', tags: [':dancer-woman:']),
      NotoEmoji(char: '💃🏾', code: '1f483_1f3fe', tags: [':dancer-woman:']),
      NotoEmoji(char: '💃🏿', code: '1f483_1f3ff', tags: [':dancer-woman:']),
    ],
    'Flags': [
      NotoEmoji(char: '🏁', code: '1f3c1', tags: [':chequered-flag:']),
      NotoEmoji(char: '🚩', code: '1f6a9', tags: [':triangular-flag:']),
      NotoEmoji(char: '🏴', code: '1f3f4', tags: [':black-flag:']),
      NotoEmoji(char: '🏳️', code: '1f3f3_fe0f', tags: [':white-flag:']),
    ],
  };
}
